package abyss.ui;
import java.util.Map;

/** Battle display dictionary; identifiers and serialized names stay in English. */
final class CombatText {
    private static final Map<String,String> ZH = Map.ofEntries(
        Map.entry("You", "你"),
        Map.entry("Status", "状态"),
        Map.entry("Elite Affix", "精英词缀"),
        Map.entry("Boss Phase", "首领阶段"),
        Map.entry("Intent", "行动预告"),
        Map.entry("Attack", "普通攻击"),
        Map.entry("Special", "特殊技能"),
        Map.entry("Attack (skill recovering)", "普通攻击（技能冷却中）"),
        Map.entry("Armored", "重甲"),
        Map.entry("Frenzied", "狂暴"),
        Map.entry("Cave Bat", "洞窟蝙蝠"),
        Map.entry("Abyss Hound", "深渊猎犬"),
        Map.entry("Lost Miner", "迷失矿工"),
        Map.entry("Shadow Assassin", "暗影刺客"),
        Map.entry("Cursed Doll", "诅咒人偶"),
        Map.entry("Bone Scholar", "白骨学者"),
        Map.entry("Void Stalker", "虚空潜猎者"),
        Map.entry("Bone Reaper", "白骨收割者"),
        Map.entry("Dread Wraith", "恐惧怨灵"),
        Map.entry("Abyss Fiend", "深渊魔怪"),
        Map.entry("Doom Herald", "末日先驱"),
        Map.entry("Abyss Lord", "深渊领主"),
        Map.entry("Relic Guardian", "圣遗物守卫"),
        Map.entry("Savage Bite", "凶猛撕咬"),
        Map.entry("Cursed Hex", "衰弱咒术"),
        Map.entry("Shadow Combo", "暗影连击"),
        Map.entry("Abyssal Rend", "深渊撕裂"),
        Map.entry("Guardian's Wrath", "守卫之怒"),
        Map.entry("Abyssal Nova", "深渊新星"),
        Map.entry("You are stunned and lose your turn!", "你被眩晕了，本回合无法行动！"),
        Map.entry("You retreat safely and keep this expedition's rewards.", "你安全撤退，保留本次冒险已经获得的奖励。"),
        Map.entry("You have no potions left!", "药水已用完！"),
        Map.entry("Skill is on cooldown for ", "技能尚需冷却 "),
        Map.entry(" more turn(s).", " 回合。"),
        Map.entry("You attack for ", "你发动普通攻击，造成 "),
        Map.entry(" damage.", " 点伤害。"),
        Map.entry(" is stunned and cannot act!", "被眩晕，无法行动！"),
        Map.entry(" attacks you for ", "攻击了你，造成 "),
        Map.entry("Ultra Nightmare [Abyssal Ward]: ", "超级噩梦【深渊护盾】："),
        Map.entry(" gains ", "获得 "),
        Map.entry(" shield.", " 点护盾。"),
        Map.entry("Elite [Armored]: ", "精英词缀【重甲】："),
        Map.entry("Elite [Frenzied]: ", "精英词缀【狂暴】："),
        Map.entry(" attack.", " 点攻击力。"),
        Map.entry("BOSS PHASE II: ", "首领进入第二阶段："),
        Map.entry(" summons ", "获得 "),
        Map.entry(" shield, gains ", " 点护盾，攻击力增加 "),
        Map.entry(" attack, and acts more aggressively!", "，行动变得更加凶猛！"),
        Map.entry("Ultra Nightmare [Abyssal Rage]: ", "超级噩梦【深渊暴怒】："),
        Map.entry("'s shield absorbs ", "的护盾吸收了 "),
        Map.entry("Your shield absorbs ", "你的护盾吸收了 "),
        Map.entry("[Phoenix Feather] blazes to life! You are revived at ", "【不死鸟之羽】燃起！你复活了，当前生命为 "),
        Map.entry(" health!", "！"),
        Map.entry("Gained ", "获得 "),
        Map.entry(" experience.", " 点经验。"),
        Map.entry(">> Reached level ", ">> 升至等级 "),
        Map.entry("! Health, attack, and defense increased. Health fully restored. <<", "！生命上限、攻击和防御提升，生命已回满。 <<"),
        Map.entry(" shrugs off the stun!", "抵抗了眩晕！"),
        Map.entry("You drink a potion and restore ", "你喝下药水，恢复 "),
        Map.entry(" health (Regen 2 turns).", " 点生命，并获得再生效果（2 回合）。"),
        Map.entry("Obtained [", "获得圣遗物【"),
        Map.entry("] - ", "】—— "),
        Map.entry("You suffer ", "你受到 "),
        Map.entry(" suffers ", "受到 "),
        Map.entry(" burn damage.", " 点灼烧伤害。"),
        Map.entry(" poison damage.", " 点中毒伤害。"),
        Map.entry("Regeneration restores ", "再生效果恢复 "),
        Map.entry(" health.", " 点生命。"),
        Map.entry("  >> CRITICAL HIT! <<", "  >> 暴击！ <<"),
        Map.entry("Passive [Iron Will]: You begin with 60 shield.", "被动【钢铁意志】：战斗开始时获得 60 护盾。"),
        Map.entry("Passive [Hunter's Focus]: A bonus hit deals ", "被动【猎手专注】：追加攻击造成 "),
        Map.entry("Passive [Execution]: ", "被动【处决】："),
        Map.entry(" has less than 65 health and is erased.", "的生命低于 65，被立即抹除。"),
        Map.entry("Passive [Divine Aegis]: You gain 8 shield.", "被动【神圣庇护】：获得 8 护盾。"),
        Map.entry("Passive [Curse]: ", "被动【诅咒】："),
        Map.entry(" takes 20% more damage for 3 turns.", "受到的伤害增加 20%，持续 3 回合。"),
        Map.entry("Casting [Armor Break]!", "施放【破甲重击】！"),
        Map.entry("Armor Break deals ", "破甲重击造成 "),
        Map.entry(" damage and sunders ", " 点伤害，并削弱了 "),
        Map.entry("'s armor!", "的护甲！"),
        Map.entry("Casting [Arcane Burst]!", "施放【奥术爆发】！"),
        Map.entry("Arcane Burst deals ", "奥术爆发造成 "),
        Map.entry(" damage and sets the foe ablaze (Burn 3 turns).", " 点伤害，并点燃敌人（灼烧 3 回合）。"),
        Map.entry("Casting [Double Shot]!", "施放【双重射击】！"),
        Map.entry("The two arrows deal ", "两支箭分别造成 "),
        Map.entry(" and ", " 和 "),
        Map.entry(" damage, and mark the target (+15% damage taken).", " 点伤害，并标记目标（受到伤害增加 15%）。"),
        Map.entry("Casting [Reality Rend]!", "施放【现实撕裂】！"),
        Map.entry("Reality Rend hit ", "现实撕裂第 "),
        Map.entry(" deals ", " 次攻击造成 "),
        Map.entry("Reality Rend deals ", "现实撕裂共造成 "),
        Map.entry(" total damage. Reality bends in your favor (+15% damage, 2 turns).", " 点伤害。现实向你倾斜：伤害增加 15%，持续 2 回合。"),
        Map.entry("Casting [Holy Judgment]!", "施放【神圣审判】！"),
        Map.entry("Holy Judgment deals ", "神圣审判造成 "),
        Map.entry(" damage and restores ", " 点伤害，并恢复 "),
        Map.entry(" is stunned for 1 turn!", "被眩晕 1 回合！"),
        Map.entry("Casting [Soul Drain]!", "施放【灵魂汲取】！"),
        Map.entry("Soul Drain deals ", "灵魂汲取造成 "),
        Map.entry(" damage, drains ", " 点伤害，吸取 "),
        Map.entry(" health, and inflicts Poison (3 turns).", " 点生命，并施加中毒（3 回合）。"),
        Map.entry("your attack is weakened (-", "你的攻击力降低（-"),
        Map.entry(", 2 turns)!", "，持续 2 回合）！"),
        Map.entry("you are set ablaze!", "你被点燃了！"),
        Map.entry(" uses [", "施放【"),
        Map.entry("]: ", "】："),
        Map.entry(" damage and ", " 点伤害，"),
        Map.entry("] and deals ", "】，造成 "),
        Map.entry(" damage!", " 点伤害！"),
        Map.entry(" uses [Shadow Combo]: two strikes deal ", "施放【暗影连击】：两次攻击分别造成 "),
        Map.entry(" uses [Abyssal Nova]: ", "施放【深渊新星】：造成 "),
        Map.entry(" damage, you are burning, and the abyss empowers him!", " 点伤害，点燃了你，并获得深渊强化！"),
        Map.entry("Blood Ruby", "血红宝石"),
        Map.entry("Iron Sigil", "钢铁徽记"),
        Map.entry("Moon Vial", "月光瓶"),
        Map.entry("Vampire Fang", "吸血鬼之牙"),
        Map.entry("Thorn Mail", "荆棘甲"),
        Map.entry("Lucky Clover", "幸运三叶草"),
        Map.entry("Alchemist Gourd", "炼金葫芦"),
        Map.entry("Gold Idol", "黄金神像"),
        Map.entry("Battle Standard", "战争旗帜"),
        Map.entry("Chrono Charm", "时光护符"),
        Map.entry("Phoenix Feather", "不死鸟之羽"),
        Map.entry("Berserker Mask", "狂战士面具"),
        Map.entry("Serpent Ring", "毒蛇戒指"),
        Map.entry("Attack +5", "攻击 +5"),
        Map.entry("Defense +4", "防御 +4"),
        Map.entry("Max health +30 and restore 30 health", "生命上限 +30，并恢复 30 生命"),
        Map.entry("Heal 15% of all damage you deal", "按造成的实际生命伤害的 15% 恢复生命"),
        Map.entry("Reflect 20% of damage taken", "反弹受到的实际生命伤害的 20%"),
        Map.entry("Critical hit chance +10%", "暴击率 +10%"),
        Map.entry("Potions restore 60% more health", "药水恢复量增加 60%"),
        Map.entry("Earn 30% more gold", "获得的金币增加 30%"),
        Map.entry("Start every battle with 30 shield", "每场战斗开始时获得 30 护盾"),
        Map.entry("Skill cooldowns reduced by 1 turn", "技能冷却减少 1 回合"),
        Map.entry("Revive once per battle at 40% health", "每场战斗可复活一次，恢复至 40% 生命"),
        Map.entry("Deal 12% more damage", "造成的伤害增加 12%"),
        Map.entry("Basic attacks inflict Poison", "普通攻击施加中毒"),
        Map.entry("[Vampire Fang] drains ", "【吸血鬼之牙】恢复 "),
        Map.entry("[Thorn Mail] reflects ", "【荆棘甲】反弹 "),
        Map.entry("[Battle Standard]: You begin with 30 extra shield.", "【战争旗帜】：战斗开始时额外获得 30 护盾。"),
        Map.entry("[Serpent Ring] venom seeps into the wound (Poison 3 turns).", "【毒蛇戒指】毒液渗入伤口（中毒 3 回合）。"),
        Map.entry("No relics remain in the abyss. You receive ", "所有圣遗物均已获得，改为获得 "),
        Map.entry(" gold instead.", " 金币。"),
        Map.entry("\nChoose one relic reward:", "\n请选择一件圣遗物奖励："),
        Map.entry("\nDefeated ", "\n击败了 "),
        Map.entry("! Gained ", "！获得 "),
        Map.entry(" gold.", " 金币。")
    );
    private CombatText() { }
    static String translate(String text) {
        if (ZH.containsKey(text)) return ZH.get(text);
        if (text.startsWith("Elite ")) return "精英·" + ZH.getOrDefault(text.substring(6), text.substring(6));
        return ZH.getOrDefault(text,text);
    }
}
