package abyss.ui;

import java.util.Map;

/** Presentation-only event, shop and trial translations. Serialized identifiers stay unchanged. */
final class WorldText {
    private WorldText() { }
    private static final Map<String, String> ZH = Map.ofEntries(
        Map.entry("Language", "语言"),
        Map.entry("Ancient Shrine", "古老神龛"), Map.entry("Locked Chest", "上锁宝箱"),
        Map.entry("Wandering Healer", "流浪医师"), Map.entry("Mystic Spring", "神秘泉水"),
        Map.entry("Trapped Adventurer", "受困冒险者"), Map.entry("Dice Gambler", "掷骰赌徒"),
        Map.entry("Ancient Library", "古老图书馆"), Map.entry("Whispering Well", "低语之井"),
        Map.entry("Masked Card Sharp", "蒙面牌手"), Map.entry("Blind Oracle", "盲眼预言家"),
        Map.entry("Relic Curator", "圣遗物收藏家"), Map.entry("Rift Gate", "裂隙之门"),
        Map.entry("Forgotten Forge", "遗忘熔炉"), Map.entry("Echoing Altar", "回响祭坛"),
        Map.entry("Moonlit Caravan", "月光商队"), Map.entry("Starved Idol", "饥饿神像"),
        Map.entry("Campfire: 1. Rest (restore 35% health)  2. Train (lose 12 health, gain 2 attack)", "篝火：1. 休息（恢复 35% 生命）  2. 训练（消耗 12 生命，增加 2 攻击）"),
        Map.entry("  3. Investigate the embers  4. Leave", "  3. 探查余烬  4. 离开"),
        Map.entry("You rest by the fire and restore ", "你在篝火旁休息，恢复 "),
        Map.entry("Training complete. Attack +2.", "训练完成，攻击 +2。"),
        Map.entry("Not enough health to train safely.", "生命不足，无法安全训练。"),
        Map.entry("You leave the crackling fire behind.", "你离开了噼啪作响的篝火。"),
        Map.entry("Merchant stock:", "商店货物："),
        Map.entry(" gold, ", " 金币，"),
        Map.entry(". Leave", ". 离开"),
        Map.entry("Not enough gold.\n", "金币不足。\n"),
        Map.entry("The merchant has sold out.", "商人的货物已售罄。"),
        Map.entry("A fire spirit blesses the camp. Restore 22 health and gain 15 shield.", "火焰精灵赐下祝福：恢复 22 生命，获得 15 护盾。"),
        Map.entry("The embers test your resolve. Lose 10 health, gain 3 attack.", "余烬考验你的意志：消耗 10 生命，增加 3 攻击。"),
        Map.entry("The embers spare your weakened body. Nothing happens.", "余烬放过了虚弱的你，无事发生。"),
        Map.entry("You find an abandoned pack: gain a potion and 1 defense.", "你发现一个遗弃的背包：获得一瓶药水，防御 +1。"),
        Map.entry("Potion", "药水"), Map.entry("gain 1 potion", "获得一瓶药水"),
        Map.entry("Whetstone", "磨刀石"), Map.entry("attack +2", "攻击 +2"),
        Map.entry("Chainmail", "锁子甲"), Map.entry("defense +2", "防御 +2"),
        Map.entry("Barrier", "魔法屏障"), Map.entry("gain 25 shield", "获得 25 护盾"),
        Map.entry("Vitality Tonic", "活力药剂"), Map.entry("max health +12; restore 20", "生命上限 +12；恢复 20 生命"),
        Map.entry("Smoke Bomb", "烟雾弹"), Map.entry("gain 1 potion and 12 shield", "获得一瓶药水与 12 护盾"),
        Map.entry("You received a potion.", "你获得了一瓶药水。"),
        Map.entry("Your weapon is sharper. Attack +2.", "武器变得更加锋利，攻击 +2。"),
        Map.entry("Your armor is reinforced. Defense +2.", "护甲得到加固，防御 +2。"),
        Map.entry("A magical barrier grants 25 shield.", "魔法屏障提供了 25 护盾。"),
        Map.entry("Vitality flows through you. Max health +12 and restore 20 health.", "活力流遍全身：生命上限 +12，恢复 20 生命。"),
        Map.entry("You pack a smoke bomb: gain a potion and 12 shield.", "你收起烟雾弹：获得一瓶药水与 12 护盾。"),
        Map.entry("You find an ancient shrine. 1. Offer 15 health for 3 attack  2. Pray to restore 20 health", "你发现一座古老神龛。1. 献祭 15 生命换取 3 攻击  2. 祈祷恢复 20 生命"),
        Map.entry("The shrine accepts your offering. Attack +3.", "神龛接受了你的献祭，攻击 +3。"),
        Map.entry("The shrine refuses an offering that would cost your life.", "神龛拒绝了会夺走你生命的献祭。"),
        Map.entry("A warm light restores 20 health.", "温暖的光芒为你恢复 20 生命。"),
        Map.entry("A locked chest blocks your path. 1. Open it  2. Leave it", "一个上锁的宝箱挡住去路。1. 打开  2. 离开"),
        Map.entry("The chest contains ", "宝箱里有 "),
        Map.entry("It was a mimic!", "竟然是宝箱怪！"),
        Map.entry("You leave the chest untouched.", "你没有碰宝箱，继续前行。"),
        Map.entry("A wandering healer offers a choice. 1. Buy a potion for 12 gold  2. Accept a risky blessing", "流浪医师给你两个选择。1. 花 12 金币购买药水  2. 接受危险的祝福"),
        Map.entry("You receive a potion.", "你获得了一瓶药水。"),
        Map.entry("Not enough gold. The healer leaves.", "金币不足，医师离开了。"),
        Map.entry("The blessing grants 2 defense.", "祝福使你的防御增加 2。"),
        Map.entry("The blessing hurts, but grants ", "祝福使你受伤，但给予你 "),
        Map.entry("A mystic spring shimmers with pale light. 1. Drink  2. Leave", "神秘泉水泛着微光。1. 饮用  2. 离开"),
        Map.entry("The water is blessed! Max health +5 and 40 health restored.", "泉水受到祝福！生命上限 +5，恢复 40 生命。"),
        Map.entry("The water is fouled! You suffer 16 damage.", "泉水已被污染！你受到 16 点伤害。"),
        Map.entry("You resist the urge and move on.", "你忍住冲动，继续前行。"),
        Map.entry("An adventurer is caught in a bear trap. 1. Free him  2. Walk away", "一名冒险者被捕兽夹困住。1. 救他  2. 离开"),
        Map.entry("He thanks you and gives ", "他感谢你，并赠予 "),
        Map.entry(" gold and a potion.", " 金币与一瓶药水。"),
        Map.entry("It was a bandit in disguise! He attacks!", "他竟是伪装的强盗，向你发起了攻击！"),
        Map.entry("You avert your eyes and move on. Somewhere behind you, a trap clicks.", "你移开目光继续前行，身后传来捕兽夹的咔嗒声。"),
        Map.entry("A dice gambler grins at you. 1. Bet 15 gold  2. Bet 40 gold  3. Bet 70 gold  4. Walk away", "掷骰赌徒向你咧嘴一笑。1. 下注 15 金币  2. 下注 40 金币  3. 下注 70 金币  4. 离开"),
        Map.entry("The gambler shrugs and vanishes into the dark.", "赌徒耸耸肩，消失在黑暗中。"),
        Map.entry("Not enough gold. The gambler laughs at you.", "金币不足，赌徒嘲笑了你。"),
        Map.entry("You roll ", "你掷出 "), Map.entry(" vs the gambler's ", " 点，赌徒掷出 "),
        Map.entry("You win ", "你赢得 "), Map.entry(" gold!", " 金币！"), Map.entry("You lose ", "你失去 "),
        Map.entry("A tie. The gambler returns your stake.", "平局，赌徒退还了你的赌注。"),
        Map.entry("An ancient library slumbers in the dark. 1. Study combat tomes (+1 attack)  2. Meditate (+1 defense)  3. Leave", "古老图书馆沉睡在黑暗中。1. 研读战斗典籍（攻击 +1）  2. 冥想（防御 +1）  3. 离开"),
        Map.entry("Hours of study sharpen your blade. Attack +1.", "数小时的研读让你的剑术更精进，攻击 +1。"),
        Map.entry("Meditation hardens your resolve. Defense +1.", "冥想坚定了你的意志，防御 +1。"),
        Map.entry("You leave the dusty shelves behind.", "你离开了布满灰尘的书架。"),
        Map.entry("A stone well whispers your name. 1. Toss 25 gold into it  2. Leave", "一口石井低声呼唤你的名字。1. 投入 25 金币  2. 离开"),
        Map.entry("The whispers fade as you leave.", "随着你离开，低语渐渐消失。"),
        Map.entry("You lack the coin. The whispers fade, disappointed.", "你的金币不足，低语失望地消散了。"),
        Map.entry("The well grants +2 attack.", "石井赐予你 2 点攻击力。"),
        Map.entry("Something rises from the well...", "有什么东西从井中缓缓升起……"),
        Map.entry("The whispers teach you fury. Attack +2.", "低语教会你愤怒，攻击 +2。"),
        Map.entry("The whispers harden your skin. Defense +2.", "低语使你的皮肤坚韧，防御 +2。"),
        Map.entry("Vitality surges through you. Max health +20 and 20 health restored.", "生命力涌遍全身：生命上限 +20，恢复 20 生命。"),
        Map.entry("A masked card sharp offers a wager. 1. Pay 25 gold for a card  2. Leave", "蒙面牌手向你发出赌局邀请。1. 花 25 金币抽牌  2. 离开"),
        Map.entry("The cards vanish into the dark.", "纸牌消失在黑暗中。"),
        Map.entry("Not enough gold. The card sharp laughs.", "金币不足，牌手发出了嘲笑。"),
        Map.entry("A golden card! You receive ", "金色纸牌！你获得 "),
        Map.entry("A silver card grants a potion and 20 shield.", "银色纸牌赐予你一瓶药水和 20 护盾。"),
        Map.entry("A cursed card cuts your hand. You suffer 14 damage.", "诅咒纸牌割伤了你的手，你受到 14 点伤害。"),
        Map.entry("A blind oracle traces circles in ash. 1. Foresee the next floor  2. Foresee two floors ahead  3. Leave", "一位盲眼预言家在灰烬中画出圆环。1. 预见下一层  2. 预见两层之后  3. 离开"),
        Map.entry("The oracle lets the ash scatter in silence.", "预言家沉默地任由灰烬散去。"),
        Map.entry("The oracle sees Abyss Floor ", "预言家看见深渊第 "),
        Map.entry(": ", "层："),
        Map.entry("an early swarm (Cave Bat, Abyss Hound, Lost Miner)", "早期怪群（洞窟蝙蝠、深渊猎犬、迷失矿工）"),
        Map.entry("Relic Guardian", "圣遗物守卫"),
        Map.entry("a shadow host (Shadow Assassin, Cursed Doll, Bone Scholar)", "暗影群落（暗影刺客、诅咒人偶、白骨学者）"),
        Map.entry("a lost legion (Void Stalker, Bone Reaper, Dread Wraith)", "迷失军团（虚空潜猎者、白骨收割者、恐惧怨灵）"),
        Map.entry("Abyss Lord", "深渊领主"),
        Map.entry("nothing beyond the final gate", "最终之门之后一片虚无"),
        Map.entry("A relic curator unlocks a velvet case. 1. Pay ", "一位圣遗物收藏家打开天鹅绒匣。1. 支付 "),
        Map.entry(" gold to examine three relics  2. Leave", " 金币查看三件圣遗物  2. 离开"),
        Map.entry("The curator closes the case and bows.", "收藏家合上匣子，向你鞠躬。"),
        Map.entry("Not enough gold. The curator keeps the case sealed.", "金币不足，收藏家没有打开匣子。"),
        Map.entry("The curator finds no relic you do not already own.", "收藏家发现你已拥有全部圣遗物。"),
        Map.entry("Choose one relic from the curator's case:", "从收藏家的匣子中选择一件圣遗物："),
        Map.entry("A rift gate hums with an elite presence. 1. Enter the rift  2. Leave", "一道裂隙之门涌动着精英气息。1. 进入裂隙  2. 离开"),
        Map.entry("The rift folds shut behind you.", "裂隙在你身后折叠闭合。"),
        Map.entry("You step through the rift. An elite guardian is waiting.", "你踏入裂隙，一名精英守卫正在等候。"),
        Map.entry("A forgotten forge still burns. 1. Temper your weapon (lose 12 health, gain 4 attack)  2. Reinforce your armor (lose 12 health, gain 4 defense)  3. Leave", "一座遗忘熔炉仍在燃烧。1. 锻打武器（消耗 12 生命，增加 4 攻击）  2. 加固护甲（消耗 12 生命，增加 4 防御）  3. 离开"),
        Map.entry("You leave the forge to its endless work.", "你让熔炉继续它永无止境的工作。"),
        Map.entry("You are too wounded to work the forge.", "你的伤势过重，无法操作熔炉。"),
        Map.entry("The forge tempers your weapon. Attack +4.", "熔炉淬炼了你的武器，攻击 +4。"),
        Map.entry("The forge reinforces your armor. Defense +4.", "熔炉加固了你的护甲，防御 +4。"),
        Map.entry("An echoing altar answers your pulse. 1. Offer 30 gold for vitality  2. Listen for a ward  3. Leave", "一座回响祭坛回应着你的脉搏。1. 献上 30 金币换取活力  2. 聆听以获得护盾  3. 离开"),
        Map.entry("The altar falls silent. You lack the required gold.", "祭坛归于沉寂，你没有足够的金币。"),
        Map.entry("The altar grants vitality. Max health +14 and 20 health restored.", "祭坛赐予活力：生命上限 +14，恢复 20 生命。"),
        Map.entry("A resonant ward forms around you.", "一道共鸣护盾在你周身形成。"),
        Map.entry("The echoes fade as you walk away.", "你走开后，回响渐渐消散。"),
        Map.entry("A moonlit caravan offers rare supplies. 1. Pay ", "一支月光商队提供稀有补给。1. 支付 "),
        Map.entry(" gold for a potion and a ward  2. Leave", " 金币获得一瓶药水与护盾  2. 离开"),
        Map.entry("The caravan fades into the mist.", "商队消失在迷雾中。"),
        Map.entry("The caravan master shakes their head. Not enough gold.", "商队主人摇了摇头，金币不足。"),
        Map.entry("You receive a potion and a moonlit ward.", "你获得一瓶药水与月光护盾。"),
        Map.entry("A starved idol opens its stone mouth. 1. Feed it 10 health for 45 gold  2. Leave", "一尊饥饿神像张开石制的嘴。1. 消耗 10 生命换取 45 金币  2. 离开"),
        Map.entry("The idol closes its mouth and goes still.", "神像合上嘴，重新沉寂。"),
        Map.entry("The idol refuses a life-threatening offering.", "神像拒绝会夺走生命的献祭。"),
        Map.entry("The idol spits out ", "神像吐出 "),
        Map.entry("The final gate opens. There is no way back.", "最终之门开启，你已无路可退。"),
        Map.entry("\nThe torches flicker. A low rumble rises beneath your feet.", "\n火炬明灭，脚下传来低沉的轰鸣。"),
        Map.entry("A hooded figure emerges from the darkness.", "一个披着兜帽的身影从黑暗中走出。"),
        Map.entry("\"Strength will not save you here. Only your next move matters.\"", "“力量在这里救不了你，唯有下一步的选择才有意义。”"),
        Map.entry("The floor fractures into tiles. Two golden cores awaken.", "地面裂成方格，两枚金色核心随之苏醒。"),
        Map.entry("The Trial of the Twin Cores begins.", "双核试炼开始。"),
        Map.entry("\nPress Enter to enter the trial...", "\n按回车进入试炼……"),
        Map.entry("The trial could not open. You return safely without a penalty.", "试炼无法开启，你安全返回，不受惩罚。"),
        Map.entry("\nThe cores shatter. The guardian crumbles, and the path back opens.", "\n核心破碎，守卫崩塌，归途重新开启。"),
        Map.entry("All relics are already yours. You receive 40 compensation gold.", "你已拥有全部圣遗物，获得 40 金币补偿。"),
        Map.entry("Choose one relic from the entire collection:", "从全部可选圣遗物中选择一件："),
        Map.entry("Health fully restored. Trial gold bonus: ", "生命已全部恢复。试炼金币奖励："),
        Map.entry("\nThe guardian seals your fate. You are cast back into the abyss, stripped of part of your fortune.", "\n守卫宣判了你的命运。你被抛回深渊，失去了部分财富。"),
        Map.entry("Trial penalty settled. Health: ", "试炼惩罚已结算。生命："),
        Map.entry("; gold lost: ", "；损失金币："), Map.entry("; relic lost: ", "；失去圣遗物："), Map.entry("none", "无"),
        Map.entry("Unable to list seed archives: ", "无法列出种子存档："),
        Map.entry("The checkpoint is damaged or incompatible. Preserved: ", "检查点损坏或不兼容，已保留原文件："),
        Map.entry("Existing archive is unreadable or completed; it will not be overwritten.", "现有存档无法读取或已结算，不会覆盖。"),
        Map.entry("Latest shortcut could not be updated. Restore using seed ", "最近存档入口更新失败，请使用种子恢复："),
        Map.entry("Achievement profile could not be read. Existing file preserved; this session is read-only.", "无法读取成就档案，原文件已保留，本次仅可查看。"),
        Map.entry("  Achievement progress is session-only: profile is read-only.", "  成就档案为只读，进度仅在本次运行中有效。"),
        Map.entry("  Achievement progress could not be saved; it remains available this session.", "  成就进度保存失败，本次运行中仍可查看。"),
        Map.entry("Another game is using this save directory. Close it before continuing.", "另一个游戏正在使用此存档目录，请先关闭它。"),
        Map.entry("Cannot safely open the save directory: ", "无法安全打开存档目录：")
    );
    static String translate(String text) { return ZH.getOrDefault(text, text); }
}
